# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Stash-Strict
version:      2.14
version_from: 
installdirs:  site
requires:
    Template:                      2.14
    Test::Exception:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
